name: Java CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml 

      - name: Run unit tests (with more detailed output)
        run: mvn test -e # Added '-e' for extended error information

      - name: Archive test reports (even on failure)
        if: always()  # This ensures reports are uploaded even if tests fail
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports/
